FROM node:22-alpine

WORKDIR /app

COPY apps/puzzles-api/package.json ./
COPY apps/puzzles-api/yarn.lock ./
COPY apps/puzzles-api ./

RUN yarn install

ENV PATH="/app/node_modules/.bin:$PATH"

CMD ["yarn", "dev"]
