FROM node:22-alpine

WORKDIR /app

COPY apps/chess-training-app/package.json ./
COPY apps/chess-training-app/yarn.lock ./
COPY apps/chess-training-app ./

RUN yarn install

ENV PATH="/app/node_modules/.bin:$PATH"

CMD ["yarn", "dev"]
